{"name": "Проверка https://dev-api.getprime.pro/api/v1/auth", "status": "failed", "statusDetails": {"message": "AssertionError: Текст не совпадает\nassert 'Домен не найден.' == 'Домен не найден'\n  \n  - Домен не найден\n  + Домен не найден.\n  ?                +", "trace": "self = <test_api.TestApiGet object at 0x000001B57DE7ED00>\n\n    @pytest.mark.apitest\n    @allure.title(\"Проверка https://dev-api.getprime.pro/api/v1/auth\")\n    @allure.description(\"Невалидная проверка с передачей ключа fronted и с неправильным доменом\")\n    def test_auth_frontend_with_wrong_domain(self):\n        url = \"https://dev-api.getprime.pro/api/v1/auth\"\n        with allure.step(f\"Проверка {url} на код 404\"):\n            assert requests.post(url=url, headers={'X-API-Key': 'aafe819e-e63c-410d-80eb-29270f45b061',\n                                                   'X-Merchant-Domain': 'wrongdomain.ru'}).status_code == 404, 'Статус код не 404'\n        response = requests.post(url=url, headers={'X-API-Key': 'aafe819e-e63c-410d-80eb-29270f45b061',\n                                                   'X-Merchant-Domain': 'wrongdomain.ru'}).json()\n        with allure.step(\n                f\"Проверка текста message. Ожидали текст 'Домен не найден, а получили '{response['message']}'\"):\n>           assert response['message'] == 'Домен не найден', \"Текст не совпадает\"\nE           AssertionError: Текст не совпадает\nE           assert 'Домен не найден.' == 'Домен не найден'\nE             \nE             - Домен не найден\nE             + Домен не найден.\nE             ?                +\n\ntest_api.py:79: AssertionError"}, "description": "Невалидная проверка с передачей ключа fronted и с неправильным доменом", "steps": [{"name": "Проверка https://dev-api.getprime.pro/api/v1/auth на код 404", "status": "passed", "start": 1751969040018, "stop": 1751969040259}, {"name": "Проверка текста message. Ожидали текст 'Домен не найден, а получили 'Домен не найден.'", "status": "failed", "statusDetails": {"message": "AssertionError: Текст не совпадает\nassert 'Домен не найден.' == 'Домен не найден'\n  \n  - Домен не найден\n  + Домен не найден.\n  ?                +\n", "trace": "  File \"C:\\Users\\Qasquad1\\PycharmProjects\\GetPrime\\tests\\test_api.py\", line 79, in test_auth_frontend_with_wrong_domain\n    assert response['message'] == 'Домен не найден', \"Текст не совпадает\"\n"}, "start": 1751969040584, "stop": 1751969040585}], "start": 1751969040018, "stop": 1751969040585, "uuid": "95120430-bbf9-488f-8397-faa9a970a227", "historyId": "ea0ea4d956e4ada3343a212a328a61a8", "testCaseId": "ea0ea4d956e4ada3343a212a328a61a8", "fullName": "tests.test_api.TestApiGet#test_auth_frontend_with_wrong_domain", "labels": [{"name": "tag", "value": "apitest"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApiGet"}, {"name": "host", "value": "Robotek3000"}, {"name": "thread", "value": "15176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}