{"name": "Проверка https://dev-api.getprime.pro/api/v1/auth - TG_SERVICE", "status": "broken", "statusDetails": {"message": "NameError: name 'tg_service_key' is not defined", "trace": "self = <test_api.TestApiGet object at 0x000001C7693C9070>\n\n    @pytest.mark.apitest\n    @allure.title(\"Проверка https://dev-api.getprime.pro/api/v1/auth - TG_SERVICE\")\n    @allure.description(\"Валидная проверка с передачей ключа tg service\")\n    def test_auth_tg_service(self):\n        global tg_service_key\n        url = \"https://dev-api.getprime.pro/api/v1/auth\"\n        with allure.step(f\"Проверка {url} на код 200\"):\n>           assert requests.post(url=url, headers={'X-API-Key':tg_service_key}).status_code == 200, \"Статус код не 200\"\nE           NameError: name 'tg_service_key' is not defined\n\ntest_api.py:87: NameError"}, "description": "Валидная проверка с передачей ключа tg service", "steps": [{"name": "Проверка https://dev-api.getprime.pro/api/v1/auth на код 200", "status": "broken", "statusDetails": {"message": "NameError: name 'tg_service_key' is not defined\n", "trace": "  File \"C:\\Users\\Qasquad1\\PycharmProjects\\GetPrime\\tests\\test_api.py\", line 87, in test_auth_tg_service\n    assert requests.post(url=url, headers={'X-API-Key':tg_service_key}).status_code == 200, \"Статус код не 200\"\n"}, "start": 1752034453487, "stop": 1752034453487}], "start": 1752034453487, "stop": 1752034453487, "uuid": "73a5a274-5024-4091-b507-701d0e32bf33", "historyId": "e802b660dc1d82bc4d54fe307d3529c3", "testCaseId": "e802b660dc1d82bc4d54fe307d3529c3", "fullName": "tests.test_api.TestApiGet#test_auth_tg_service", "labels": [{"name": "tag", "value": "apitest"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApiGet"}, {"name": "host", "value": "Robotek3000"}, {"name": "thread", "value": "5460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}